/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimoniosRouteImport } from './routes/testimonios'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as PorQueOrpheusRouteImport } from './routes/por-que-orpheus'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiarioIndexRouteImport } from './routes/diario/index'
import { Route as DiarioSlugRouteImport } from './routes/diario/$slug'

const TestimoniosRoute = TestimoniosRouteImport.update({
  id: '/testimonios',
  path: '/testimonios',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PorQueOrpheusRoute = PorQueOrpheusRouteImport.update({
  id: '/por-que-orpheus',
  path: '/por-que-orpheus',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioIndexRoute = DiarioIndexRouteImport.update({
  id: '/diario/',
  path: '/diario/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioSlugRoute = DiarioSlugRouteImport.update({
  id: '/diario/$slug',
  path: '/diario/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/empresas': typeof EmpresasRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/por-que-orpheus': typeof PorQueOrpheusRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/testimonios': typeof TestimoniosRoute
  '/diario/$slug': typeof DiarioSlugRoute
  '/diario/': typeof DiarioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/empresas': typeof EmpresasRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/por-que-orpheus': typeof PorQueOrpheusRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/testimonios': typeof TestimoniosRoute
  '/diario/$slug': typeof DiarioSlugRoute
  '/diario': typeof DiarioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/empresas': typeof EmpresasRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/por-que-orpheus': typeof PorQueOrpheusRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/testimonios': typeof TestimoniosRoute
  '/diario/$slug': typeof DiarioSlugRoute
  '/diario/': typeof DiarioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/empresas'
    | '/politica-de-cookies'
    | '/politica-de-privacidad'
    | '/por-que-orpheus'
    | '/preguntas-frecuentes'
    | '/servicios'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/testimonios'
    | '/diario/$slug'
    | '/diario/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/empresas'
    | '/politica-de-cookies'
    | '/politica-de-privacidad'
    | '/por-que-orpheus'
    | '/preguntas-frecuentes'
    | '/servicios'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/testimonios'
    | '/diario/$slug'
    | '/diario'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/empresas'
    | '/politica-de-cookies'
    | '/politica-de-privacidad'
    | '/por-que-orpheus'
    | '/preguntas-frecuentes'
    | '/servicios'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/testimonios'
    | '/diario/$slug'
    | '/diario/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  ContactoRoute: typeof ContactoRoute
  EmpresasRoute: typeof EmpresasRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  PorQueOrpheusRoute: typeof PorQueOrpheusRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  ServiciosRoute: typeof ServiciosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreMiRoute: typeof SobreMiRoute
  TestimoniosRoute: typeof TestimoniosRoute
  DiarioSlugRoute: typeof DiarioSlugRoute
  DiarioIndexRoute: typeof DiarioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonios': {
      id: '/testimonios'
      path: '/testimonios'
      fullPath: '/testimonios'
      preLoaderRoute: typeof TestimoniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/por-que-orpheus': {
      id: '/por-que-orpheus'
      path: '/por-que-orpheus'
      fullPath: '/por-que-orpheus'
      preLoaderRoute: typeof PorQueOrpheusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario/': {
      id: '/diario/'
      path: '/diario'
      fullPath: '/diario/'
      preLoaderRoute: typeof DiarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario/$slug': {
      id: '/diario/$slug'
      path: '/diario/$slug'
      fullPath: '/diario/$slug'
      preLoaderRoute: typeof DiarioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  ContactoRoute: ContactoRoute,
  EmpresasRoute: EmpresasRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  PorQueOrpheusRoute: PorQueOrpheusRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  ServiciosRoute: ServiciosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreMiRoute: SobreMiRoute,
  TestimoniosRoute: TestimoniosRoute,
  DiarioSlugRoute: DiarioSlugRoute,
  DiarioIndexRoute: DiarioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
